10 LET NUMBER = 5
20 CALL FACTORIAL
30 EXIT PROGRAM

SUB FACTORIAL
    LET COUNT = 0
    LET RESULT = 1
    WHILE COUNT < NUMBER
        LET COUNT = COUNT + 1
        LET RESULT = RESULT * COUNT
    END WHILE
END SUB
