10 LET NUMBER = 5
20 CALL FACTORIAL
30 EXIT PROGRAM

REM CALCULATE FACTORIAL OF THE NUMBER
SUB FACTORIAL
    REM INITIALIZE VARIABLES
    LET COUNT = 0
    LET RESULT = 1
    WHILE TRUE
        IF COUNT = NUMBER
            REM BREAK FROM LOOP
            EXIT WHILE
        END IF
        LET COUNT = COUNT + 1
        LET RESULT = RESULT * COUNT
    END WHILE
    REM RESET COUNTER
    LET COUNT = 0
END SUB
